title: C O D E I C U
description: >- # this means to ignore newlines until "baseurl:"
  Code Recording
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://codeicu.github.io" # the base hostname & protocol for your site, e.g. http://example.com

theme: minima
plugins:
  - jekyll-feed
