title: "CODE ICU"
description: >- # this means to ignore newlines until "baseurl:"
  Code Recording
  标题没啥意思,就是好玩
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://codeicu.github.io" # the base hostname & protocol for your site, e.g. http://example.com

theme: jekyll-theme-hacker
plugins:
  - jekyll-feed
show_downloads: false
